### ISSUE TITLE
v2.0.2 on Win10 - Combinations and Special Keys not working

### ISSUE THREAD

**Issue by bmeredyk** [JeffreyDavidsz/VICREO-Listener#29]
How close to working is the nodejs based preview supposed to be? Windows 10, Vicreo-Listener 2.0.2 preview build with latest Companion 2.0 Beta build seems to only barely work. The only pieces that I can get to do anything is a single keypress or typing a string message.

Key Combinations, for example CTRL + c and CTRL + v do to a copy & paste don't seem to do anything. Same for Special Keys - for example the Windows key.

Open a File also does not appear to be working for example, setting up a button with "C:\Windows\System32\calc.exe" fails to open the calculator app. (Tried both with and without the quotes)

I did specify while adding the Vicreo instance to Companion that it is the nodejs build. No previous versions of Vicreo are running.

**Comment by Tw0bit** [comment]
I can confirm I too have issues with Vicreo 2.0.2 and Companion Beta 2.0.0-29d8d90-2402 on Windows.

My use case: open a PPT file, change it to full screen/play, then next/previous. I cannot get the following to work:
- Vicreo Open File - NOT WORKING (Workaround - use Companion's Internal Run shell path)
- Vicreo Hotkey - Space and Back-Arrow works; but not F5

I will be testing the Mac version shortly.

Summary: I have been able to get single keys (back arrow, space) to work, but not F5.

**Comment by Tw0bit** [comment]
On OSx, It appears that Open File and Hotkey with F-keys do not work either.

Also the OSx-specific command "Send keypress to MacOS Process" doesnt work. I have tried the process name "powerpoint", "PowerPoint" and "Microsoft PowerPoint" sending just Space (next slide) and left arror (previous slide) and doesnt work. I have just one process of Powerpoint open.

**Comment by JeffreyDavidsz** [comment]
I need to check whats wrong. The latest build of companion doesn't work while running it locally, everything works, I'll update soon

**Comment by Tw0bit** [comment]
My testing was on localhost/same device. Companion however was set to my network ip as I was using the emulator on a tablet to push the buttons.

**Comment by bmeredyk** [comment]
Same as above, Companion and Vicreo running on same computer and using web buttons.

**Comment by JeffreyDavidsz** [comment]
Above is fixed in new release. Updated companion also, but you should be able to use older versions of companioin

**Comment by bmeredyk** [comment]
JeffreyDavidsz, I hate to say it but it is still not working for me. Freshly downloaded and installed Companion 2 and Vicreo 2.0.3.  The Vicreo Logs show the commands coming across but nothing actually happens.

**Comment by JeffreyDavidsz** [comment]
Did you gave VICREO permission to control your computer?
Is the instance in Companion sending version > 2.0 or below?

**Comment by JeffreyDavidsz** [comment]
Is you are seeing { key: etc in the log you are on the new syntax otherwise on the old. Both options should work and tested, but I need a bit more information to see where the issue is coming from

**Comment by bmeredyk** [comment]
> Did you gave VICREO permission to control your computer?
> Is the instance in Companion sending version > 2.0 or below?

Nothing ever asked for permission to control the computer. When is that supposed to appear (Win10)?
Yes, the instance of Vicreo configured in Companion is "Version >2.0"

**Comment by bmeredyk** [comment]
> Is you are seeing { key: etc in the log you are on the new syntax otherwise on the old. Both options should work and tested, but I need a bit more information to see where the issue is coming from

Here's the logs after a few key presses
15:20:23 { "key":"v", "type":"press", "modifiers":["ctrl"] }
15:20:23 {"key":"v","type":"press","modifiers":["ctrl"]}
15:20:20 { "key":"c", "type":"press", "modifiers":["ctrl"] }
15:20:20 {"key":"c","type":"press","modifiers":["ctrl"]}
15:20:14 { "type":"file","path":""C:/Windows/System32/calc.exe"" }
15:20:9 { "key":"F5", "type":"press", "modifiers":[] }
15:20:9 {"key":"F5","type":"press","modifiers":[]}
15:20:1 { "key":"F5", "type":"press", "modifiers":[] }
15:20:1 {"key":"F5","type":"press","modifiers":[]}
15:19:2 connected

**Comment by JeffreyDavidsz** [comment]
try option/alt tab (combo)

**Comment by bmeredyk** [comment]
> try option/alt tab (combo)

That seems to get a reaction, the usual Windows display of all windows briefly flashes and then active window switches

**Comment by JeffreyDavidsz** [comment]
open file works for me. ('C:/Users/JeffreyDavidsz/Desktop/brightsign/Testbeeld-1920x1080_full-hd.png') but opening iexplorer, gives a not found I'll look into that. The ctrl command should be control in the new version. I'll change it

**Comment by bmeredyk** [comment]
> open file works for me. ('C:/Users/JeffreyDavidsz/Desktop/brightsign/Testbeeld-1920x1080_full-hd.png') but opening iexplorer, gives a not found I'll look into that. The ctrl command should be control in the new version. I'll change it

OK, if I try the open file with C:\Windows\System32\calc.exe (no quotes) that correctly opens the calculator app - BUT Vicreo also exits (crashes?)

If I try it with 'C:\Windows\System32\calc.exe' (single quoted) then I get a file not found error dialog.    If I try it with "C:\Windows\System32\calc.exe" (double quoted) then nothing at all happens although the log does show receiving the command.

**Comment by JeffreyDavidsz** [comment]
Found the bugs and fixed them. I'll build a 2.0.4 any second. Thanks for your testing. Use the open file without quotes, it crashed because of a test that was still in place

**Comment by bmeredyk** [comment]
Tested 2.0.4 and it seems to work much better - thank you!

One part I found that wasn't working still was the "Printscreen (No Mac)*" special key which didn't seem to cause anything to happen on Windows either.  F# function keys and the Windows key worked fine though.

**Comment by arigolan** [comment]
Hi, 

I'm new to Vicreo. Using v 2.0.9 on mac OSX 10.14.6 (Mojave)
Using Stream Deck and Companion 2.1.0 on a remote computer on the LAN.

I've gotten VICREO hotkey: Combination to work just fine for "Command" + N, which I've set as a Keyboard Shortcut in mimoLive to trigger "next slide". And I've got "Command" + Tab to peform it's normal function of cycling through apps (which I can use to bring mimoLive to the foreground (make it the Active app), so I'm communicating fine between the companion server (mac mini) and the remote machine (on the same LAN) running mimoLive. However, the app needs to be in the foreground for the "next slide" trigger to work. So I've tried adding the action of "Open file" for both the app itself, as well as trying it for the document (just to force it to the foreground) with no luck. I also tried  Vicreo "Send To Process" mimoLive, with no apparent results, other than an error msg in the Vicreo Log window 
"please change to new syntax"
"received ...whatever the command was..." 

I've read this thread eagerly thinking maybe those functions just were not working, but it seems you mention having fixed the bugs. Have you confirmed on Mac OSX that "Open File" and/or "Send to Process" are working?

I tried both with and without using " " before and after the app name, and/or the file name.
Before I read the thread, I thought maybe I was messing up the file path. I've used Terminal, Option right-clicking to copy path name, and dragging to the "Go to Folder" window- to confirm file path. I even tried adding adding the cd command that Terminal shows when doing the above over the network. All with no results.

I'm hoping this is just a bug on mac and I'm not that incompetent :)

Assuming it is, hopefully it can be easily fixed. If not, is there anything you can suggest testing, and I'll gladly report back to you?

Also, assuming thing are working as expected, is "Open File" the best method for bringing an app to the foreground? If not, please consider the feature request for a preset but to "Activate App".

Int the meantime, thanks for the awesome program, and please keep up the great work!

> Found the bugs and fixed them. I'll build a 2.0.4 any second. Thanks for your testing. Use the open file without quotes, it crashed because of a test that was still in place
